import { Roboto } from "next/font/google";
import Body from "@/UI/Body/Body";
import "./globals.scss";
import type { Metadata } from "next";

const inter = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
	title: "Shop course next13 masters",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={inter.className}>
			<Body>{children}</Body>
		</html>
	);
}
